### ISSUE TITLE
auto-alt-ref can have any value between 0 and 6 in VP9

### ISSUE THREAD

**Issue by GDXN** [deterenkelt/Nadeshiko#15]
another VP9 documentation error found.... 
VP9 the codec where its documentation is it biggest drawback, it even hurt it in comparisons.

I discovered it looking at:
https://chromium.googlesource.com/webm/libvpx/+/refs/tags/v1.8.0
confirmation:
https://bugs.chromium.org/p/webm/issues/detail?id=1597

**Comment by deterenkelt** [comment]
Thanks for the report, I shall do a couple of test encodes and, if auto-alt-ref=6 would seem to improve quality or speed, I’ll change the default in example.nadeshiko.rc.sh. And probably update RCFILE_MINVER too.

**Comment by deterenkelt** [comment]
The [tests](/deterenkelt/Nadeshiko/wiki/Tests.-VP9:-auto%E2%80%91alt%E2%80%91ref-1-and-6) with Nadeshiko are complete, default setting for `libvpx_auto_alt_ref` is updated in [v2.4.2](https://github.com/deterenkelt/Nadeshiko/releases/tag/v2.4.2). 

I didn’t force a config update this time, because some people may not see a purpose in it until they update their libvpx. Also some may find the update rather damaging the quality.

**Comment by RX14** [comment]
Support for this doesn't seem to be in an ffmpeg relese yet: https://github.com/FFmpeg/FFmpeg/commit/55e021f39b02e838672582dbe94fe279bfc8328c

The check for supporting this needs to check ffmpeg version not libvpx version.

**Comment by deterenkelt** [comment]
Argh. This is a problem, thanks for reporting it.

Since there’s no way to compare FFmpeg versions that do not bear an assigned number (only commit versions), the only way would be either to add yet another config option to enable extra values for `-auto-alt-ref`, or to figure out what version of libavcodec appeared after this commit. This is feasible, but will take some time.

libvpx version must still be checked, for even FFmpeg from Git still depends on >=libvpx-1.4.0.

I’ll try to release a fix asap.

**Comment by RX14** [comment]
@deterenkelt how about simply changing the default back until an ffmpeg release supporting it is cut, then change it back with this check. Alternatively, just try to encode and grep the error message.

**Comment by deterenkelt** [comment]
Regressions? That’s for the weak.  https://i.imgur.com/rRjO6k1.jpg

So far I’ve found, that the `ffmpeg -version` of the tree with that commit returns libavcodec version `58. 39.100 / 58. 39.100`. So Nadeshiko should check if libavcodec version is higher than that. However, this slash is disturbing, guess it’s time to go to IRC and ask directly.

Also this commit dates back to 3 November 2018, and it supposedly should’ve make it to the last stable release of FFmpeg, that is 4.1.1 issued this February. Please tell, which version of FFmpeg you are using?

**Comment by RX14** [comment]
@deterenkelt it's ffmpeg 4.1.1, but the commit must have made it into a development branch and not been picked for the release because you can check that the patch isn't in the 4.1.1 git tag: https://github.com/FFmpeg/FFmpeg/blob/n4.1.1/libavcodec/libvpxenc.c#L1070

**Comment by deterenkelt** [comment]
Thanks, going back to 4.1.1 is bound to difficulties, but the [article on videohelp](https://www.videohelp.com/software/ffmpeg/version-history) about the 4.1.1 release mentions the library versions, and the libavcodec included there apparently has a version `58. 35.100` (lower than `58.39.100` observed in the tree with a commit), so I guess a check on that version would do. No extra config option is needed or reverting to the old behaviour is needed, `auto-alt-ref`  will just be automatically set to 1, if requirements for anything higher won’t be met.

**Comment by RX14** [comment]
My libavcodec is `libavcodec     58. 35.100 / 58. 35.100` so this should work

**Comment by deterenkelt** [comment]
A check for libavcodec version added in [v2.5.7](https://github.com/deterenkelt/Nadeshiko/releases/tag/v2.5.7).
